apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: b8sykyl2m-nodejs 
  janus-idp.io/tekton: b8sykyl2m-nodejs
  backstage.io/kubernetes-id: b8sykyl2m-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b8sykyl2m-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml