apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b8sykyl2m-nodejs
  janus-idp.io/tekton: b8sykyl2m-nodejs
  backstage.io/kubernetes-id: b8sykyl2m-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b8sykyl2m-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
